### PR TITLE
Fix featured stories section

### LINKED ISSUE #1099: Fix Featured Stories section in scholarx summer page
**Describe the bug**
The [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/) `Featured Stories` section is empty. The data is not visible in this section.

**To Reproduce**
1. Go to [https://sefglobal.org/scholarx/2021/summer/](https://sefglobal.org/scholarx/2021/summer/)
2. Scroll down to 'Featured Stories'
3. See that the blogs are missing

**Expected behavior**
The data(blogs) should be populated in this section.

### PR DESCRIPTION
**Pull request by miniskynet**
## Purpose

The purpose of this PR is to fix #1099 

## Goals

To populate the featured stories section and add a functionality to hide the entire section if no featured stories are available

## Approach

1) Navigate to `scholarx\2021\summer\index.html`
2) Give an id to featured stories section.
3) Give an id to "SEE MORE" button
4) Navigate to `scholarx\2021\functions.js`
5) Add an if statement to the `loadFeaturedStories` function to hide the featured stories section if the length of loaded data is 0 (no date available)

### Screenshots

**Original (Featured stories section is empty) :** 
image
**After (Stories have been populated) :** 
image

  
### Preview Link

https://pr-1103-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: scholarx/2021/functions.js [hunk 1]
```diff
@@ -103,8 +103,13 @@ function loadFeaturedStories() {
         dataType: 'json',
         success: function (data) {
             document.getElementById('btnFeaturedStories').style.visibility = "visible";
+            
+            //hide section if there are no featured Stories
+            if (data.length == 0){
+              document.getElementById("featured-stories-section").style.display = "none";
+            }
```
Comment (Piumal1999) [inline scholarx/2021/functions.js]: I think this way would be better
```suggestion
            
            //hide section if there are no featured Stories
            if (data.length == 0){
              document.getElementById("featured-stories-section").style.display = "none";
            } else if (data.length >=6) {
                //slice array to two parts
                let partOne = data.slice(0, 6);
```

**Review by Piumal1999 — COMMENTED** [review]
Well done @miniskynet . Added a small suggestion

File: scholarx/2021/functions.js (hunk 1 above)
Comment (miniskynet) [reply scholarx/2021/functions.js]: Hello @Piumal1999 thank you for the feedback. Are you suggesting that I bring up the `else if` block near the closing bracket of the `if` block. Because I can't seem to find any syntactical difference in your suggestion apart from that. If there are, please be kind enough to let me know. Thank you :)

Comment (Piumal1999) [reply scholarx/2021/functions.js]: > Are you suggesting that I bring up the else if block near the closing bracket of the if block.

yes exactly

Comment (miniskynet) [reply scholarx/2021/functions.js]: @Piumal1999 what would happen if I commit suggestion as follows:
image
Or do I need to make changes and amend?

Comment (Piumal1999) [reply scholarx/2021/functions.js]: Make the changes and amend. Commit suggestion button will not do the required change in this case

Comment (miniskynet) [reply scholarx/2021/functions.js]: please take a look now :)

Comment (miniskynet) [reply scholarx/2021/functions.js]: @Piumal1999

**Comment by miniskynet** [comment]
@janethavi @anjula-sack can you guys please take a look?

**Review by janethavi — APPROVED** [review]
LGTM! Good work @miniskynet

**Review by anjula-sack — APPROVED** [review]
Thank you! @miniskynet
