### PR TITLE
Use CheckBoxes to implement Mentor/Mentee Dropdown

### LINKED ISSUE #1576: Use CheckBoxes to implement Mentor/Mentee Dropdown
**Describe the bug**
Currently, we use a dropdown to manage mentor/mentee sections on ScholarX archive. But we have to use checkboxes instead of dropdown

**To Reproduce**
1. Go to ScholarX archive
2. See error

**Expected behavior**
Able to manage mentor/mentee sections using checkboxes instead of dropdowns.

**Additional context**
No

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1576 

## Goals

Adding CheckBoxes to implement Mentor/Mentee Dropdown

## Approach

I added CheckBoxes to implement Mentor/Mentee Dropdown

### Screenshots

Mentors

image

Mentees

image

  
### Preview Link

https://pr-1579-sef-site.surge.sh/scholarx/archive

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: scholarx/archive/functions.js [hunk 1]
```diff
@@ -263,40 +248,70 @@ function filterByYear() {
...
-    } else{
+        filteredMentors = mentors.filter((mentor) => selectedYears.includes(mentor.year));
+        filteredMentees = mentees.filter((mentee) => selectedYears.includes(mentee.year));
+        renderProfiles(filteredMentors, filteredMentees);
+    } else {
         filterByIndustry("")
     }
 }
-function openMentorProfile(index){
+$(document).ready(function () {
```
Comment (YoshithaRathnayake) [inline scholarx/archive/functions.js]: From here I have edited @anjula-sack 
Sorry mistakenly it is formatted.

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake 
1. we have to show the university filter on the mentee's side and the industry filter on the mentors' page.


2. 
image
think that you have already selected the mentor's checkbox, when you select the mentee's checkbox again we should uncheck the mentor's checkbox. every time there needs to be just only one selection from these two checkboxes. (you can't select both two checkboxes at the same time)

3. Also we need to use the same checkboxes theme that we used to other checkboxes.

**Comment by YoshithaRathnayake** [comment]
@janithlahirukariyawasam I change the checkbox but I can't click it can you tell me what is that error please?

**Comment by janithlahirukariyawasam** [comment]
> @janithlahirukariyawasam I change the checkbox but I can't click it can you tell me what is that error please?

It is little bit hard to understand because you have used the prettier. 
But I think this is a conflict that occurs as a result of a **id** issue. Can you check the unique ids you gave to the checkboxes with relevant js code.

**Comment by YoshithaRathnayake** [comment]
> > @janithlahirukariyawasam I change the checkbox but I can't click it can you tell me what is that error please?
> 
> It is little bit hard to understand because you have used the prettier. But I think this is a conflict that occurs as a result of a **id** issue. Can you check the unique ids you gave to the checkboxes with relevant js code.

Sure and I found the method to that problem (you can't select both two checkboxes at the same time)

File: scholarx/archive/index.html [hunk 2]
```diff
@@ -67,11 +67,18 @@
...
-        <div class="mt-2 mb-5">
-            <select id="selection" class="btn btn-secondary dropdown-toggle" >
-                <option value="mentors">Mentors</option>
-                <option value="mentees">Mentees</option>
-            </select>
+        <div class="mt-2 mb-5" id="selection">
+        <div class="mt-2 mb-5" id="selection">
+            <button class="btn btn-sm custom-checkbox mb-3 py-2 btn-checkbox">
+                <input class="custom-control-input" id="mentorsCheckbox" type="checkbox">
+                <label class="custom-control-label" for="mentors">mentors</label>
```
Comment (janithlahirukariyawasam) [inline scholarx/archive/index.html]:
```suggestion
                <label class="custom-control-label" for="mentorsCheckbox">mentors</label>
```
You have to use the id you gave to **"input"** tag for **"for"** attribute.

Comment (YoshithaRathnayake) [reply scholarx/archive/index.html]: Ok

**Comment by YoshithaRathnayake** [comment]
Now it's ok right? no problems? @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
You have fixed a lot of issues @YoshithaRathnayake 
but when we load this page for the first time both mentor & mentee pages will appear. So you have to fix it.
image

**Comment by YoshithaRathnayake** [comment]
> You have fixed a lot of issues @YoshithaRathnayake but when we load this page for the first time both mentor & mentee pages will appear. So you have to fix it. image

Ah yes so which one I should show when loading for the first time mentors or mentees? mentors right? @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake It needs to be mentors 

You can run a code that checks the mentor checkbox when you load this page every time.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake It needs to be mentors
> 
> You can run a code that checks the mentor checkbox when you load this page every time.

It has already given a display none to the mentee page but its not hiding why is that?

File: scholarx/archive/functions.js [hunk 3]
```diff
@@ -263,40 +248,83 @@ function filterByYear() {
...
+        filteredMentees = mentees.filter((mentee) => selectedYears.includes(mentee.year));
+        renderProfiles(filteredMentors, filteredMentees);
+    } else {
         filterByIndustry("")
     }
 }
-function openMentorProfile(index){
+//mentor mentee selection
+$(document).ready(function () {
+    $('#selection').on('change', function () {
```
Comment (janithlahirukariyawasam) [inline scholarx/archive/functions.js]:
```suggestion
    function handlePageTransition() { ...
```
Instead of **change** we can create a function like this and use **onClick** attribute in **input** tags

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Ok that's also done but that mentee page is not hiding I make to keep the mentors checked when it is loaded again and again but mentee page?

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake almost finished!  there is a function called loadData(), You have to write a code line to check the mentor checkbox

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake almost finished! there is a function called loadData(), You have to write a code line to check the mentor checkbox

I did now its checked when loading the page
Check  now but mentee page still there @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> > @YoshithaRathnayake almost finished! there is a function called loadData(), You have to write a code line to check the mentor checkbox
> 
> I did now its checked when loading the page Check now

image
let put this code after underlined code.
 document.getElementById('mentorsCheckbox').checked = true;

**Comment by YoshithaRathnayake** [comment]
Sure but that mentee page is still visible when loading @janithlahirukariyawasam Is there a solution for that @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> Sure but that mentee page is still visible when loading @janithlahirukariyawasam

$("#showMentees").hide()
can you put this to loadData() function also. @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
image

image


 
There is a display: block; in the html code but I can't find it on the real code. If I can remove that the problem will solve definitely @janithlahirukariyawasam

**Comment by YoshithaRathnayake** [comment]
> > Sure but that mentee page is still visible when loading @janithlahirukariyawasam
> 
> $("#showMentees").hide() can you put this to loadData() function also. @YoshithaRathnayake

Yes I added it after the document.getElementById('mentorsCheckbox').checked = true; but it didn't work @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> > > Sure but that mentee page is still visible when loading @janithlahirukariyawasam
> > 
> > 
> > $("#showMentees").hide() can you put this to loadData() function also. @YoshithaRathnayake
> 
> Yes I added it after the document.getElementById('mentorsCheckbox').checked = true; but it didn't work @janithlahirukariyawasam
image
In CSS file can you add **!important** like this and check it again   @YoshithaRathnayake 
**Check what happen after you select Mentees Checkbox also?**

File: scholarx/archive/functions.js [hunk 4]
```diff
@@ -263,40 +249,79 @@ function filterByYear() {
...
+        if (mentorsCheckbox.checked) {
+            uncheckCheckboxes();
+            renderAllProfiles();
+            $("#showMentors").show();
+            $("#showMentees").hide();
+            $("#university-filter").hide();
+            $("#industry-filter").show();
+        }
+    });
+}
```
Comment (janithlahirukariyawasam) [inline scholarx/archive/functions.js]:
```suggestion
function mentorsCheckout() {
     uncheckCheckboxes();
     renderAllProfiles();
     $("#showMentors").show();
     $("#showMentees").hide();
     $("#university-filter").hide();
     $("#industry-filter").show();
}
```

What happen if you write the code this way?

**Comment by YoshithaRathnayake** [comment]
> > > > Sure but that mentee page is still visible when loading @janithlahirukariyawasam
> > > 
> > > 
> > > $("#showMentees").hide() can you put this to loadData() function also. @YoshithaRathnayake
> > 
> > 
> > Yes I added it after the document.getElementById('mentorsCheckbox').checked = true; but it didn't work @janithlahirukariyawasam
> > image
> > In CSS file can you add **!important** like this and check it again   @YoshithaRathnayake
> > **Check what happen after you select Mentees Checkbox also?**

image

Output when doing like that I think we have to remove it from the js @janithlahirukariyawasam

File: scholarx/archive/functions.js (hunk 4 above)
Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Yeah its also working I'll update like this @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake Yes

**Comment by janithlahirukariyawasam** [comment]
image
@YoshithaRathnayake like this, there are lot of places we have to do the changes in function.js. That will solve this issue

**Comment by YoshithaRathnayake** [comment]
> image @YoshithaRathnayake like this, there are lot of places we have to do the changes in function.js. That will solve this issue

so I should put hide to every $("#showMentees") codes in the functions.js file? @janithlahirukariyawasam

File: scholarx/archive/functions.js [hunk 5]
```diff
@@ -117,25 +97,25 @@ async function loadData() {
...
+    } else if (document.getElementById("selection").value === "mentees") {
         $("#showMentees").show();
     }
 }
-function renderProfiles(mentorYear,menteeYear) {
+function renderProfiles(mentorYear, menteeYear) {
     noRsultsPageHelper();
     //show no results page if sorted mentor or mentee array is empty
-    if(document.getElementById("selection").value === "mentors" && mentorYear.length === 0){
+    if (document.getElementById("selection").value === "mentors" && mentorYear.length === 0) {
```
Comment (janithlahirukariyawasam) [inline scholarx/archive/functions.js]:
```suggestion
    if (document.getElementById('mentorsCheckbox').checked == true && mentorYear.length === 0) {
```
like this?

Comment (janithlahirukariyawasam) [reply scholarx/archive/functions.js]: After you change every places like this. It will work, I checked it with my code & It worked.

Comment (janithlahirukariyawasam) [reply scholarx/archive/functions.js]: @YoshithaRathnayake

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: ok

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Yes! It's working. Thank you very much @janithlahirukariyawasam

File: scholarx/archive/functions.js [hunk 6]
```diff
@@ -117,25 +97,25 @@ async function loadData() {
...
 loadData();
 //this function run in every  render profiles functions to reset the page structure based on the selection
-function noRsultsPageHelper(){
+function noRsultsPageHelper() {
     $("#noResultsMessage").hide();
-    if(document.getElementById("selection").value === "mentors"){
+    if (document.getElementById('mentorsCheckbox').checked == true) {
         $("#showMentors").show();
-    }else if(document.getElementById("selection").value === "mentees"){
+    } else if (document.getElementById("selection").value === "mentees") {
```
Comment (janithlahirukariyawasam) [inline scholarx/archive/functions.js]:
```suggestion
    } else if (document.getElementById('menteesCheckbox').checked == true) {
```
Also @YoshithaRathnayake you have to replace every these places in function.js

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Yeah I did @janithlahirukariyawasam searched and replaced in VS Code

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Now that problem is also fixed no?

Comment (janithlahirukariyawasam) [reply scholarx/archive/functions.js]: Good Job @YoshithaRathnayake , But we replaced the dropdown with checkboxes, so also the above places need to be changed, if not there can be issues when it working Eg: filtering issues like that . can you change every places like below
image

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Yeah I changed I searched in visual studio code and replaced them. Are there any codes that have not changed? @janithlahirukariyawasam

Comment (YoshithaRathnayake) [reply scholarx/archive/functions.js]: Yeah I thought only mentors now I changed the mentees too @janithlahirukariyawasam check whether its ok now?

**Comment by janithlahirukariyawasam** [comment]
image

**Comment by YoshithaRathnayake** [comment]
> image

I can't see the image @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake there is function call renderProfiles() in that you have to do a change.

**Comment by YoshithaRathnayake** [comment]
Now it's ok right? @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> Now it's ok right? @janithlahirukariyawasam

Good Job @YoshithaRathnayake ! Now it is fine.

**Comment by YoshithaRathnayake** [comment]
> > Now it's ok right? @janithlahirukariyawasam
> 
> Good Job @YoshithaRathnayake ! Now it is fine.

Thanks @janithlahirukariyawasam for helping me

**Review by anjula-sack — APPROVED** [review]
Good job! @YoshithaRathnayake
